### ISSUE TITLE
Please provide a QR code matching template for app use

### ISSUE THREAD

**Issue by wanghao926** [QOSGroup/qmoon#140]
Hi, ~
Please provide a QR code parsing matching rule for payment generated by different wallets，easyzone use this rule to parse data. 
Thank u

**Comment by MattWangming** [comment]
<img width="952" alt="QCR" src="https://user-images.githubusercontent.com/37991051/63313378-c575e900-c336-11e9-9828-feb89f05db71.png">
Here is the conclusion for the QR code pattern

**Comment by MattWangming** [comment]
1. a service will be provided to return all the elements with `string` format for app side combination usage.

2. integrated into Qmoon API services

**Comment by MattWangming** [comment]
Here is the commit for this feature at primary solution: [fix commit in webinjumio](https://github.com/MattWangming/WebInJumio/commit/baea1667f737e575c307fd4f1b78b766771b99e4)

**Comment by MattWangming** [comment]
close it with positive feedback from Front end
